
HEADERS += \
    NodeSystem/Derived/math/printnode.h \
    NodeSystem/Derived/math/addnode.h \
    NodeSystem/Derived/math/var1d.h \
    NodeSystem/Derived/math/nodevaluefinder.h \
    NodeSystem/Derived/math/subtract.h \
    NodeSystem/Derived/math/resultparser.h \
    NodeSystem/Derived/math/multiplynode.h \
    NodeSystem/Derived/math/cursor.h \
    NodeSystem/Derived/math/dividenode.h \
    NodeSystem/Derived/math/modulonode.h \
    NodeSystem/Derived/math/sinnode.h \
    NodeSystem/Derived/math/cosnode.h \
    NodeSystem/Derived/math/tannode.h \
    NodeSystem/Derived/math/asinnode.h \
    NodeSystem/Derived/math/acosnode.h \
    NodeSystem/Derived/math/atannode.h \
    NodeSystem/Derived/math/atan2node.h \
    NodeSystem/Derived/math/hypotnode.h \
    NodeSystem/Derived/math/lognode.h \
    NodeSystem/Derived/math/pownode.h \
    NodeSystem/Derived/math/expnode.h \
    NodeSystem/Derived/math/sqrtnode.h \
    NodeSystem/Derived/math/asinhnode.h \
    NodeSystem/Derived/math/acoshnode.h \
    NodeSystem/Derived/math/atanhnode.h \
    NodeSystem/Derived/math/coshnode.h \
    NodeSystem/Derived/math/sinhnode.h \
    NodeSystem/Derived/math/tanhnode.h \
    NodeSystem/Derived/math/pinode.h \
    NodeSystem/Derived/math/econstnode.h \
    NodeSystem/Derived/math/degreesnode.h \
    NodeSystem/Derived/math/radiansnode.h \
    NodeSystem/Derived/math/erfnode.h \
    NodeSystem/Derived/math/erfcnode.h \
    NodeSystem/Derived/math/gammanode.h \
    NodeSystem/Derived/math/lgammanode.h \
    NodeSystem/Derived/math/ceilnode.h \
    NodeSystem/Derived/math/fabsnode.h \
    NodeSystem/Derived/math/factorialnode.h \
    NodeSystem/Derived/math/floornode.h \
    NodeSystem/Derived/math/frexpnode.h


SOURCES += \
    NodeSystem/Derived/math/printnode.cpp \
    NodeSystem/Derived/math/addnode.cpp \
    NodeSystem/Derived/math/var1d.cpp \
    NodeSystem/Derived/math/subtract.cpp \
    NodeSystem/Derived/math/multiplynode.cpp \
    NodeSystem/Derived/math/dividenode.cpp \
    NodeSystem/Derived/math/modulonode.cpp \
    NodeSystem/Derived/math/sinnode.cpp \
    NodeSystem/Derived/math/cosnode.cpp \
    NodeSystem/Derived/math/tannode.cpp \
    NodeSystem/Derived/math/asinnode.cpp \
    NodeSystem/Derived/math/acosnode.cpp \
    NodeSystem/Derived/math/atannode.cpp \
    NodeSystem/Derived/math/atan2node.cpp \
    NodeSystem/Derived/math/hypotnode.cpp \
    NodeSystem/Derived/math/lognode.cpp \
    NodeSystem/Derived/math/pownode.cpp \
    NodeSystem/Derived/math/expnode.cpp \
    NodeSystem/Derived/math/sqrtnode.cpp \
    NodeSystem/Derived/math/asinhnode.cpp \
    NodeSystem/Derived/math/acoshnode.cpp \
    NodeSystem/Derived/math/atanhnode.cpp \
    NodeSystem/Derived/math/coshnode.cpp \
    NodeSystem/Derived/math/sinhnode.cpp \
    NodeSystem/Derived/math/tanhnode.cpp \
    NodeSystem/Derived/math/pinode.cpp \
    NodeSystem/Derived/math/econstnode.cpp \
    NodeSystem/Derived/math/degreesnode.cpp \
    NodeSystem/Derived/math/radiansnode.cpp \
    NodeSystem/Derived/math/erfnode.cpp \
    NodeSystem/Derived/math/erfcnode.cpp \
    NodeSystem/Derived/math/gammanode.cpp \
    NodeSystem/Derived/math/lgammanode.cpp \
    NodeSystem/Derived/math/ceilnode.cpp \
    NodeSystem/Derived/math/fabsnode.cpp \
    NodeSystem/Derived/math/factorialnode.cpp \
    NodeSystem/Derived/math/floornode.cpp \
    NodeSystem/Derived/math/frexpnode.cpp
